DROP TABLE SGCOM.ARTICULO;
DROP TABLE SGCOM.SUBCATEGORIA;
DROP TABLE SGCOM.CATEGORIA;
DROP TABLE SGCOM.MEDIDA;

CREATE TABLE SGCOM.CATEGORIA (
	CATEGORIA_ID INTEGER(3) NOT NULL AUTO_INCREMENT,
    CODIGO VARCHAR(25) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    PRIMARY KEY (CATEGORIA_ID)
);
CREATE UNIQUE INDEX PK_CATEGORIA ON SGCOM.CATEGORIA (CATEGORIA_ID);
CREATE UNIQUE INDEX IX_CATEGORIA_CODIGO ON SGCOM.CATEGORIA(CODIGO);

/*CREATE TABLE SGCOM.SUBCATEGORIA (
	SUBCATEGORIA_ID INTEGER(3) NOT NULL AUTO_INCREMENT,
    CATEGORIA_ID INTEGER(3) NOT NULL,
    CODIGO VARCHAR(25) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    PRIMARY KEY (SUBCATEGORIA_ID)
);
CREATE UNIQUE INDEX PK_SUBCATEGORIA ON SGCOM.SUBCATEGORIA (SUBCATEGORIA_ID);
ALTER TABLE SGCOM.SUBCATEGORIA ADD CONSTRAINT FOREIGN KEY FK_SUBCATEGORIA_CATEGORIA (CATEGORIA_ID) REFERENCES SGCOM.CATEGORIA (CATEGORIA_ID); 
CREATE UNIQUE INDEX IX_SUBCATEGORIA_CODIGO ON SGCOM.SUBCATEGORIA(CODIGO);

CREATE TABLE SGCOM.MEDIDA (
	MEDIDA_ID INTEGER(4) NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(255) NOT NULL,
    SIMBOLO VARCHAR(2) NOT NULL,
    PRIMARY KEY (MEDIDA_ID)
);
CREATE UNIQUE INDEX PK_MEDIDA ON SGCOM.MEDIDA (MEDIDA_ID);
*/
CREATE TABLE SGCOM.ARTICULO (
	ARTICULO_ID INTEGER(10) NOT NULL AUTO_INCREMENT,
    CODIGO VARCHAR(20) NOT NULL,
    CODIGO_BARRA VARCHAR(13),
    CATEGORIA_ID INTEGER(3),
    /*SUBCATEGORIA_ID INTEGER(2),*/
    DESCRIPCION VARCHAR(255),
    /*DETALLE_MEDIDA INTEGER(10) NOT NULL,*/
    /*MEDIDA_ID INTEGER(4),*/
    COSTO FLOAT,
    DESCUENTO FLOAT,
    DESCUENTO_APLICADO FLOAT,
    EXCENTO BOOLEAN,
    UTILIDAD FLOAT,
    PRECIO_VENTA FLOAT,
    PRECIO_VENTA2 FLOAT,
    CANTIDAD INTEGER,
    /*MINIMO INTEGER,
    AGRUPADO BOOLEAN,
    INVENTARIO BOOLEAN,*/
    PRIMARY KEY (ARTICULO_ID)
);
-- ADD FK - MEDIDAS
CREATE UNIQUE INDEX PK_ARTICULO ON SGCOM.ARTICULO (ARTICULO_ID);
ALTER TABLE SGCOM.ARTICULO ADD CONSTRAINT FK_ARTICULO_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES SGCOM.CATEGORIA (CATEGORIA_ID);
/*ALTER TABLE SGCOM.ARTICULO ADD CONSTRAINT FK_ARTICULO_MEDIDA FOREIGN KEY (MEDIDA_ID) REFERENCES SGCOM.MEDIDA (MEDIDA_ID);    */