INSERT INTO CATEGORIA (CODIGO, DESCRIPCION) VALUES ('PLASTICO','BOLSAS Y PLASTICOS');
INSERT INTO CATEGORIA (CODIGO, DESCRIPCION) VALUES ('FERRETERIA','FERRETERIA Y HERRAMIENTAS');
INSERT INTO CATEGORIA (CODIGO, DESCRIPCION) VALUES ('LIBRERIA','LIBREARIA Y PAPELERIA');
INSERT INTO CATEGORIA (CODIGO, DESCRIPCION) VALUES ('OTROS','OTROS');
COMMIT;

SELECT * FROM CATEGORIA